[font.normal]
family = "IntoneMono Nerd Font Mono"

[font]
size = 13

[window.padding]
x = 30
y = 30

[window]
opacity = 0.9

[env]
TERM = "xterm-256color"

# Default colors
[colors.primary]
background = '#0b0c0f'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
